import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "vi";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.menu": "Menu", 
    "nav.about": "About",
    "nav.blog": "Blog",
    "nav.contact": "Contact",
    "nav.reservations": "Reservations",
    
    // Hero Section
    "hero.tagline": "CONNECTING HEARTS, AUTHENTIC VIETNAMESE TASTE",
    "hero.title": "HUM'S PIZZA",
    "hero.subtitle": "Where authentic Vietnamese flavors meet modern culinary artistry. Creating memorable moments for every family through exceptional food and warm experiences.",
    "hero.orderOnline": "Order Online",
    "hero.bookTable": "Book a Table",
    "hero.orderMenu": "Order Now",
    
    // Menu
    "menu.appetizers": "Appetizers",
    "menu.mainCourse": "Main Course",
    "menu.desserts": "Desserts", 
    "menu.beverages": "Beverages",
    "menu.available": "Available",
    "menu.soldOut": "Sold Out",
    "menu.addToCart": "Add to Cart",
    "menu.featuredDishes": "Featured Dishes", 
    "menu.all": "All",
    "menu.ourSignatureDishes": "Our Signature Dishes",
    "menu.viewFullMenu": "View Full Menu",
    "menu.searchPlaceholder": "Search menu items...",
    "menu.subtitle": "Discover our full collection of Vietnamese and international dishes, each crafted with premium ingredients and traditional techniques",
    "menu.searchOurMenu": "Search our menu...",
    "menu.noItemsFound": "No items found matching your search.",
    "menu.allItems": "All Items",
    "menu.tryAdjusting": "Try adjusting your search terms or browse all categories.",
    
    // Category translations
    "category": "Category",
    "category.appetizers": "Appetizers",
    "category.mainCourses": "Main Courses", 
    "category.desserts": "Desserts",
    "category.teaSelection": "Tea Selection",
    "category.beverages": "Beverages",
    "category.soups": "Soups",
    
    // Customization Management
    "customization.management": "Customization Management",
    "customization.addCustomization": "Add Customization",
    "customization.createNew": "Create New Schema",
    "customization.editSchema": "Edit Schema",
    "customization.nameEn": "Name (English)",
    "customization.nameVi": "Name (Vietnamese)",

    "customization.schemaType": "Schema Type",
    "customization.sizeSelection": "Size Selection",
    "customization.halfAndHalf": "Half & Half Pizza",
    "customization.additionalToppings": "Additional Toppings",
    "customization.comboConfiguration": "Combo Configuration",
    "customization.serviceFee": "Service Fee",
    "customization.addComboItem": "Add Combo Item",
    "customization.comboPrice": "Combo Price",
    "customization.originalPrice": "Original Price",
    "customization.discountAmount": "Discount Amount",
    "customization.save": "Save",
    "customization.cancel": "Cancel",
    "customization.delete": "Delete",
    "customization.edit": "Edit",
    "customization.activate": "Activate",
    "customization.active": "Active",
    "customization.createSuccess": "Schema created successfully!",
    "customization.updateSuccess": "Schema updated successfully!",
    "customization.deleteSuccess": "Schema deleted successfully!",
    "customization.cloneSuccess": "Schema cloned successfully!",
    "customization.confirmDelete": "Are you sure you want to delete this schema?",
    "customization.selectSchemaType": "Select schema type",
    "customization.descriptionEn": "Description (English)",
    "customization.descriptionVi": "Description (Vietnamese)",
    "customization.priceConfig": "Price Configuration",
    "customization.halfAndHalfFee": "Half & Half Service Fee (VND)",
    "customization.size18cmPrice": "Size 18cm Price (+VND)",
    
    // Privacy Policy
    "privacy.title": "Privacy Policy",
    "privacy.lastUpdated": "Last Updated",
    "privacy.date": "August 13, 2025",
    "privacy.section1.title": "Information We Collect",
    "privacy.section1.content1": "At Hum's Pizza, we collect information you provide directly to us, such as when you make a reservation, place an order, or contact us for customer service.",
    "privacy.section1.content2": "We may also automatically collect certain information about your device and how you interact with our website, including your IP address, browser type, and pages visited.",
    "privacy.section2.title": "Personal Information",
    "privacy.section2.content1": "The types of personal information we may collect include:",
    "privacy.section2.item1": "Name and contact information (email, phone number)",
    "privacy.section2.item2": "Reservation details and dining preferences", 
    "privacy.section2.item3": "Order history and payment information",
    "privacy.section2.item4": "Communication preferences and feedback",
    "privacy.section3.title": "How We Use Your Information",
    "privacy.section3.content1": "We use the information we collect to:",
    "privacy.section3.item1": "Process reservations and orders",
    "privacy.section3.item2": "Provide customer service and support",
    "privacy.section3.item3": "Send you updates about our restaurant and services",
    "privacy.section3.item4": "Improve our website and dining experience",
    "privacy.section4.title": "Information Sharing",
    "privacy.section4.content": "We do not sell, trade, or otherwise transfer your personal information to third parties without your consent, except as described in this Privacy Policy or as required by law.",
    "privacy.section5.title": "Data Security",
    "privacy.section5.content": "We implement appropriate security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.",
    "privacy.section6.title": "Contact Us",
    "privacy.section6.content1": "If you have any questions about this Privacy Policy or our privacy practices, please contact us at:",
    "privacy.contact.email": "Email",
    "privacy.contact.phone": "Phone",
    "privacy.contact.address": "Address",
    
    // Terms of Service
    "terms.title": "Terms of Service",
    "terms.lastUpdated": "Last Updated", 
    "terms.date": "August 13, 2025",
    "terms.section1.title": "Acceptance of Terms",
    "terms.section1.content1": "By accessing and using Hum's Pizza's website and services, you accept and agree to be bound by the terms and provision of this agreement.",
    "terms.section1.content2": "If you do not agree to abide by the above, please do not use this service.",
    "terms.section2.title": "Use License",
    "terms.section2.content1": "Permission is granted to temporarily download one copy of the materials on Hum's Pizza's website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:",
    "terms.section2.item1": "Modify or copy the materials",
    "terms.section2.item2": "Use the materials for any commercial purpose or for any public display",
    "terms.section2.item3": "Attempt to reverse engineer any software contained on the website",
    "terms.section2.item4": "Remove any copyright or other proprietary notations from the materials",
    "terms.section3.title": "Disclaimer",
    "terms.section3.content": "The materials on Hum's Pizza's website are provided on an 'as is' basis. Hum's Pizza makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.",
    "terms.section4.title": "Limitations",
    "terms.section4.content": "In no event shall Hum's Pizza or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on Hum's Pizza's website, even if Hum's Pizza or an authorized representative has been notified orally or in writing of the possibility of such damage.",
    "terms.section5.title": "Contact Information",
    "terms.section5.content1": "If you have any questions about these Terms of Service, please contact us at:",
    "terms.contact.email": "Email",
    "terms.contact.phone": "Phone",
    "terms.contact.address": "Address",
    
    // Accessibility
    "accessibility.title": "Accessibility Statement",
    "accessibility.lastUpdated": "Last Updated",
    "accessibility.date": "August 13, 2025", 
    "accessibility.section1.title": "Our Commitment",
    "accessibility.section1.content": "Hum's Pizza is committed to ensuring digital accessibility for people with disabilities. We are continually improving the user experience for everyone and applying the relevant accessibility standards.",
    "accessibility.section2.title": "Accessibility Features",
    "accessibility.section2.item1": "Keyboard navigation support",
    "accessibility.section2.item2": "Screen reader compatibility", 
    "accessibility.section2.item3": "High contrast color options",
    "accessibility.section2.item4": "Scalable text and interface elements",
    "accessibility.section3.title": "Feedback",
    "accessibility.section3.content": "We welcome your feedback on the accessibility of Hum's Pizza. Please let us know if you encounter accessibility barriers on our website.",
    "accessibility.section4.title": "Contact Us",
    "accessibility.section4.content1": "If you have accessibility concerns or suggestions, please contact us:",
    "accessibility.contact.email": "Email",
    "accessibility.contact.phone": "Phone",
    "accessibility.contact.address": "Address",
    
    // Featured Sections
    "featured.title": "Experience Excellence",
    "featured.signature.title": "Signature Cuisine",
    "featured.signature.description": "Authentic Vietnamese flavors elevated with modern culinary techniques",
    "featured.atmosphere.title": "Elegant Atmosphere",
    "featured.atmosphere.description": "Sophisticated dining environment perfect for any occasion",
    "featured.service.title": "Exceptional Service",
    "featured.service.description": "Personalized attention from our dedicated culinary team",
    
    // Reservation Section
    "reservation.title": "Reserve Your Experience",
    "reservation.subtitle": "Book your table and let us create an unforgettable culinary journey for you",
    "reservation.bookNow": "Book Now",
    
    // Reviews Section
    "reviews.title": "What Our Guests Say",
    "reviews.subtitle": "Genuine feedback from our guests about their dining experience at Hum's Pizza",
    
    // Blog Section
    "blog.title": "Latest Stories",
    "blog.subtitle": "Stay updated with our culinary adventures and restaurant news",
    "blog.whatsHappening": "What's Happening",
    "blog.blogSubtitle": "Stay updated with our latest events, seasonal menus, culinary inspirations, and behind-the-scenes stories from Hum's Pizza",
    "blog.readMore": "Read More",
    "blog.readFullArticle": "Read Full Article",
    "blog.moreStories": "More Stories",
    "blog.viewAll": "View All Posts",
    "blog.noPosts": "No Posts Yet",
    "blog.noPostsDesc": "We're working on bringing you exciting content about our culinary journey.",
    "blog.checkBack": "Check back soon for updates, recipes, and behind-the-scenes stories!",
    "blog.postNotFound": "Post Not Found",
    "blog.postNotFoundDesc": "The post you're looking for doesn't exist or has been removed.",
    "blog.backToBlog": "Back to News",
    "blog.publishedBy": "Published by",
    "blog.moreArticles": "More Articles",
    
    // Booking
    "booking.title": "Reserve Your Table",
    "booking.date": "Date",
    "booking.time": "Time", 
    "booking.selectTime": "Select Time",
    "booking.guests": "Guests",
    "booking.guest": "Guest",
    "booking.name": "Full Name",
    "booking.email": "Email",
    "booking.emailOptional": "Email (Optional)",
    "booking.phone": "Phone Number",
    "booking.requests": "Special Requests",
    "booking.requestsOptional": "Special Requests (Optional)",
    "booking.requestsPlaceholder": "Dietary restrictions, special occasions, seating preferences...",
    "booking.confirm": "Confirm Reservation",
    "booking.confirming": "Confirming...",
    "booking.cancel": "Cancel",
    "booking.success": "Reservation Confirmed!",
    "booking.successMessage": "We'll contact you to confirm shortly.",
    
    // Admin
    "admin.menuManagement": "Menu Management",
    "admin.homeManagement": "Home Management", 
    "admin.aboutManagement": "About Management",
    "admin.addItem": "Add Menu Item",
    "admin.edit": "Edit",
    "admin.delete": "Delete",
    "admin.name": "Name",
    "admin.nameVi": "Name (Vietnamese)",
    "admin.description": "Description", 
    "admin.descriptionVi": "Description (Vietnamese)",
    "admin.price": "Price",
    "admin.category": "Category",
    "admin.image": "Image",
    "admin.uploadImage": "Upload Image",
    "admin.tags": "Tags",
    "admin.status": "Status",
    "admin.available": "Available",
    "admin.unavailable": "Sold Out",
    "admin.save": "Save",
    "admin.cancel": "Cancel",
    "admin.create": "Create",
    "admin.update": "Update",
    
    // Footer
    "footer.description": "Where authentic Vietnamese flavors meet modern culinary artistry, creating memorable moments for every family through exceptional food and warm experiences.",
    "footer.hours": "Hours",
    "footer.contact": "Contact",
    "footer.contactUs": "Contact Us",
    "footer.address": "Address",
    "footer.addressLine1": "108 Ngo Gia Tu Street, Chanh Nghia Ward",
    "footer.addressLine2": "Thu Dau Mot City, Binh Duong Province, Vietnam",
    "footer.hotline": "Hotline",
    "footer.email": "Email",
    "footer.follow": "Follow Us",
    "footer.newsletter": "Newsletter",
    "footer.subscribe": "Subscribe to our newsletter for updates",
    "footer.emailPlaceholder": "Enter your email",
    "footer.subscribeBtn": "Subscribe",
    "footer.allRights": "All rights reserved.",
    "footer.tagline": "Where culinary artistry meets Vietnamese tradition",
    
    // About Page
    "about.title": "About Hum's Pizza",
    "about.subtitle": "Where handmade pizza meets Vietnamese hospitality, creating warm memories for families through delicious food and heartfelt service.",
    "about.ourStory": "Our Story",
    "about.story1": "Hum's Pizza started as a small shop in Bình Dương, built with passion and craftsmanship. Our team learned from traditional pizzas from Chicago and Italy while adapting flavors to suit Vietnamese tastes.",
    "about.story2": "From sauce and toppings to service style, everything is carefully considered to make our pizza feel familiar and enjoyable. Beyond making delicious pizza, we aim to be a place for memorable moments.",
    "about.story3": "Each table can host important conversations, first dates, or simple family meals. We treasure this and strive to create a warm, welcoming space where customers always feel at home.",
    "about.ourPhilosophy": "Our Philosophy",
    "about.vision": "Our Vision",
    "about.visionDesc": "Hum's Pizza aims to build a Vietnamese pizza restaurant chain that meets international standards while maintaining its unique identity. Our goal is not only to provide high-quality food but also to create connections and memorable experiences.",
    "about.mission": "Our Mission", 
    "about.missionDesc": "We make handmade pizzas with consistent quality, balanced flavors, and sincere service. We create an experience from aroma and taste to space and service, believing that great memories start from simple things like a delicious pizza.",
    "about.values": "Core Values",
    "about.valuesDesc": "We believe in handcrafted quality, dedication in every dish, and creating a warm space where every family can create memorable moments together through delicious food.",
    "about.meetTeam": "Meet Our Team",

    // Statistics Section - English
    "stats.recipes": "Special Pizza Recipes",
    "stats.served": "Vietnamese-Style Pizzas Served",
    "stats.fresh": "Fresh Dough Daily",
    "stats.satisfaction": "Customer Satisfaction",

    // Team Section - English
    "team.chefHung": "Mr. Hung",
    "team.chefHungTitle": "Head Chef & Founder",
    "team.chefHungDesc": "With over 10 years of pizza-making experience, Mr. Hung has researched and adapted recipes to create pizzas that maintain traditional essence while suiting Vietnamese tastes.",
    "team.mai": "Ms. Mai",
    "team.maiTitle": "Restaurant Manager",
    "team.maiDesc": "Ms. Mai ensures every customer has the best experience possible. She constantly listens to feedback and improves service quality to create a warm space for all families.",
    "team.tuan": "Mr. Tuan",
    "team.tuanTitle": "Pizza Dough Specialist",
    "team.tuanDesc": "Mr. Tuan oversees the daily dough-making and fermentation process, ensuring every pizza has a crispy, tender crust with the distinctive flavor of authentic Vietnamese-style pizza.",
    
    // Contact Page
    "contact.title": "Contact Us",
    "contact.subtitle": "Get in touch with us for reservations, inquiries, or special events",
    "contact.visitUs": "Visit Us",
    "contact.address": "108 Ngô Gia Tự, Phường Chánh Nghĩa, Thủ Dầu Một, Bình Dương",
    "contact.phone": "0934 699 798",
    "contact.email": "support@humspizza.com",
    "contact.hours": "Opening Hours",
    "contact.sendMessage": "Send us a Message",
    "contact.yourName": "Your Name",
    "contact.yourEmail": "Your Email",
    "contact.yourPhone": "Your Phone",
    "contact.subject": "Subject",
    "contact.message": "Your Message",
    "contact.sendBtn": "Send Message",
    "contact.sending": "Sending...",
    "contact.messageSent": "Message Sent!",
    "contact.messageSuccess": "We'll get back to you as soon as possible.",
    "contact.messageFailed": "Failed to Send Message",
    

    
    // Legal Pages
    "legal.privacyPolicy": "Privacy Policy",
    "legal.termsOfService": "Terms of Service",
    "legal.accessibility": "Accessibility",
    "legal.navigation": "Navigation",
    "legal.legalText": "Legal",
    
    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.close": "Close",
    "common.home": "Home",
    "common.menu": "Menu",
    "common.about": "About",
    "common.blog": "News",
    "common.contact": "Contact",
    "common.booking": "Booking",
    
    // Admin Dashboard - Status translations
    "admin.pending": "Pending",
    "admin.confirmed": "Confirmed", 
    "admin.completed": "Completed",
    "admin.cancelled": "Cancelled",
    "admin.preparing": "Preparing",
    "admin.ready": "Ready",
    
    // Admin Dashboard - Form labels
    "admin.customerName": "Customer Name",
    "admin.specialRequests": "Special Requests",
    "admin.orderType": "Order Type",
    "admin.totalAmount": "Total Amount",
    "admin.items": "Items",
    
    // Admin Dashboard - Modal titles
    "admin.editReservation": "Edit Reservation",
    "admin.editOrder": "Edit Order",
    "admin.updateReservationInfo": "Update reservation information",
    "admin.updateOrderInfo": "Update order information",
    
    // Admin Dashboard - Additional
    "admin.dashboardTitle": "Admin Dashboard",
    "admin.welcomeBack": "Welcome back",
    "admin.viewWebsite": "View Website", 
    "admin.logout": "Logout",
    "admin.totalReservations": "Total Reservations",
    "admin.pendingReservations": "Pending Reservations", 
    "admin.totalOrders": "Total Orders",
    "admin.pendingOrders": "Pending Orders",
    "admin.reservationManagement": "Reservation Management",
    "admin.orderManagement": "Order Management",
    "admin.blogManagement": "News Management",
    "admin.reviewManagement": "Customer Reviews Management",
    "admin.contactManagement": "Contact Message Management",
    
    // Tab names (shorter)
    "admin.reservationTab": "Reservations",
    "admin.orderTab": "Orders",
    "admin.menuTab": "Menu",
    "admin.blogTab": "News",
    "admin.reviewTab": "Reviews",
    "admin.contactTab": "Messages",
    "admin.reservationList": "Reservation List",
    "admin.reservationSubtitle": "Manage customer reservation requests",
    "admin.orderList": "Order List",
    "admin.orderSubtitle": "Manage customer orders",
    "admin.reviewList": "Customer Reviews List",
    "admin.reviewSubtitle": "Manage and moderate customer reviews and feedback",
    "admin.contactList": "Contact Messages",
    "admin.contactSubtitle": "Manage customer inquiries and contact messages",
    "admin.newsTitle": "News Management",
    "admin.newsSubtitle": "Manage blog posts and news articles", 
    "admin.searchReservations": "Search by name, phone, email...",
    "admin.searchOrders": "Search by name, email, order code...",
    "admin.allTime": "All Time",
    "admin.today": "Today",
    "admin.last7Days": "Last 7 Days", 
    "admin.last30Days": "Last 30 Days",
    "admin.last90Days": "Last 90 Days",
    "admin.last180Days": "Last 180 Days",
    "admin.showing": "Showing",
    "admin.noReservationsFound": "No reservations found matching filters",
    "admin.noOrdersFound": "No orders found matching filters",
    "admin.noReservations": "No reservations yet",
    "admin.noOrders": "No orders yet",
    "admin.confirmBtn": "Confirm",
    "admin.cancelBtn": "Cancel",
    "admin.confirmedStatus": "Confirmed", 
    "admin.pendingStatus": "Pending",
    "admin.completedStatus": "Completed",
    "admin.cancelledStatus": "Cancelled",
    "admin.selectItems": "Select items to view details...",
    "admin.reservations": "reservations",
    "admin.orders": "orders",
    "admin.at": "at",
    "admin.people": "people",
    "admin.requests": "Requests",
    "admin.menuTitle": "Menu Management",
    "admin.menuSubtitle": "Add, edit, remove and organize menu items and categories",
    "admin.menuItems": "Menu Items",
    "admin.categories": "Categories",
    "admin.manageCategories": "Manage Categories",
    "admin.manageCategoryItems": "Manage category items in menu",
    "admin.categoryManagement": "Category Management",
    "admin.addCategory": "Add Category",
    "admin.editCategory": "Edit Category",
    "admin.categoryName": "Category Name (English)",
    "admin.categoryNameVi": "Category Name (Vietnamese)",
    "admin.categoryDescription": "Category Description",
    "admin.sortOrder": "Sort Order",
    "admin.searchMenu": "Search by item name, description, tags...",
    "admin.allCategories": "All Categories",
    "admin.showingItems": "Showing",
    "admin.itemsLabel": "items",
    
    // Additional admin keys
    "admin.customizationTab": "Customization",
    "admin.customizationManagement": "Customization Management",
    "admin.dineIn": "Dine In",
    "admin.takeout": "Takeout", 
    "admin.delivery": "Delivery",
    "admin.total": "Total",
    "admin.orderedItems": "Ordered Items",
    "admin.selectItemToAdd": "Select item to add",
    "admin.searchFood": "Search for food...",
    "admin.add": "Add",
    "admin.noItemsFound": "No items found with keyword",
    
    // Dashboard Statistics Cards
    "admin.totalReservationsCard": "Total Reservations",
    "admin.totalOrdersCard": "Total Orders", 
    "admin.totalMessagesCard": "Total Messages",
    
    // Search and Filters
    "admin.searchPlaceholder": "Search reservations, orders, messages...",
    "admin.allTimeFilter": "All Time",
    "admin.todayFilter": "Today",
    "admin.last7DaysFilter": "Last 7 Days",
    "admin.last30DaysFilter": "Last 30 Days",
    "admin.last90DaysFilter": "Last 90 Days",
    "admin.saving": "Saving...",
    
    // Home Management
    "home.management.title": "Home Management",
    "home.management.subtitle": "Manage homepage content and hero videos",
    "home.hero.title": "Hero Title",
    "home.hero.titleVi": "Hero Title (Vietnamese)",
    "home.hero.titleEn": "Hero Title (English)",
    "home.reservation.title": "Reservation Title", 
    "home.reservation.titleVi": "Reservation Title (Vietnamese)",
    "home.reservation.titleEn": "Reservation Title (English)",
    "home.reservation.subtitle": "Reservation Subtitle",
    "home.reservation.subtitleVi": "Reservation Subtitle (Vietnamese)", 
    "home.reservation.subtitleEn": "Reservation Subtitle (English)",
    "home.featured.title": "Featured Title",
    "home.featured.titleVi": "Featured Title (Vietnamese)",
    "home.featured.titleEn": "Featured Title (English)",
    "home.featured.subtitle": "Featured Subtitle", 
    "home.featured.subtitleVi": "Featured Subtitle (Vietnamese)",
    "home.featured.subtitleEn": "Featured Subtitle (English)",
    "home.update": "Update Homepage",
    "home.videoHero": "Hero Videos",
    "home.uploadMainVideo": "Upload Main Hero Video",
    "home.uploadReservationVideo": "Upload Reservation Hero Video",
    "home.mainVideoDesc": "Upload background video for main hero section (max 200MB)",
    "home.reservationVideoDesc": "Upload background video for reservation experience section (max 200MB)",
    "home.uploadMainBtn": "Upload Hero Video",
    "home.uploadReservationBtn": "Upload Reservation Video", 
    "home.videoNote": "Note: Videos will be used as background for homepage hero sections. Ensure videos are high quality and suitable for restaurant branding.",
    "home.refresh": "Refresh",
    "home.featuredSection.title": "Featured Section",
    "home.featuredSection.subtitle": "Title of the signature dishes section",
    "home.reservationSection.title": "Reservation Section", 
    "home.reservationSection.subtitle": "Title of the reservation experience section",
    "home.reviewsSection.title": "Customer Reviews Section",
    "home.reviewsSection.subtitle": "Title of the what customers say section",
    "home.blogSection.title": "News Section",
    "home.blogSection.subtitle": "Title of the latest stories section",
    "home.labels.titleEn": "Title (English)",
    "home.labels.titleVi": "Title (Vietnamese)",
    "home.labels.subtitleEn": "Subtitle (English)",
    "home.labels.subtitleVi": "Subtitle (Vietnamese)",
    
    // About Management
    "about.management.title": "About Management",
    "about.management.subtitle": "Manage about page content and restaurant information",
    "about.tabs.statistics": "Statistics",
    "about.tabs.philosophy": "Philosophy",
    "about.tabs.team": "Team",
    "about.stats.title": "Statistics",
    "about.stats.subtitle": "Restaurant statistics and numbers",
    "about.philosophy.title": "Our Philosophy",
    "about.philosophy.subtitle": "Vision, mission and core values",
    "about.team.title": "Team",
    "about.team.subtitle": "Information about team members",
    "about.labels.titleEn": "Title (English)",
    "about.labels.titleVi": "Title (Vietnamese)",
    "about.labels.contentEn": "Content (English)",
    "about.labels.contentVi": "Content (Vietnamese)",
    "about.labels.memberName": "Member Name",
    "about.labels.sectionTitle": "Section Title (English)",
    "about.labels.sectionTitleVi": "Section Title (Vietnamese)",
    "about.vision.title": "Vision",
    "about.mission.title": "Mission", 
    "about.values.title": "Core Values",
    "about.update": "Update About Page", 
    "about.story.title": "Our Story Title",
    "about.story.titleVi": "Our Story Title (Vietnamese)",
    "about.story.titleEn": "Our Story Title (English)",
    "about.story.content": "Our Story Content",
    "about.story.contentVi": "Our Story Content (Vietnamese)",
    "about.story.contentEn": "Our Story Content (English)", 
    "about.mission.titleVi": "Mission Title (Vietnamese)",
    "about.mission.titleEn": "Mission Title (English)",
    "about.mission.content": "Mission Content",
    "about.mission.contentVi": "Mission Content (Vietnamese)",
    "about.mission.contentEn": "Mission Content (English)",
    "about.vision.titleVi": "Vision Title (Vietnamese)", 
    "about.vision.titleEn": "Vision Title (English)",
    "about.vision.content": "Vision Content",
    "about.vision.contentVi": "Vision Content (Vietnamese)",
    "about.vision.contentEn": "Vision Content (English)",
    "about.values.titleVi": "Core Values Title (Vietnamese)",
    "about.values.titleEn": "Core Values Title (English)",
    "about.values.content": "Core Values Content",
    "about.values.contentVi": "Core Values Content (Vietnamese)",
    "about.values.contentEn": "Core Values Content (English)",
    
    // Login Page
    "login.title": "Hum's Pizza",
    "login.subtitle": "Login to admin dashboard",
    "login.username": "Username",
    "login.password": "Password",
    "login.loginButton": "Login",
    "login.loggingIn": "Logging in...",
    "login.demoInfo": "Demo login information:",
    "login.demoUsername": "Username:",
    "login.demoPassword": "Password:",
    
    // Account Settings
    "account.title": "Account Settings",
    "account.subtitle": "Manage your account and user permissions",
    "account.myProfile": "My Profile",
    "account.userManagement": "User Management",
    "account.profileInfo": "Profile Information",
    "account.updateInfo": "Update your personal information and change your password",
    "account.fullName": "Full Name",
    "account.email": "Email",
    "account.changePassword": "Change Password",
    "account.currentPassword": "Current Password",
    "account.newPassword": "New Password (Optional)",
    "account.leaveBlank": "Leave blank to keep current",
    "account.confirmPassword": "Confirm New Password",
    "account.updating": "Updating...",
    "account.updateProfile": "Update Profile",
    "account.manageUsers": "Manage admin and staff accounts",
    "account.addUser": "Add User",
    "account.editUser": "Edit User",
    "account.addNewUser": "Add New User",
    "account.createAccount": "Create a new admin or staff account",
    "account.updateAccount": "Update user information",
    "account.username": "Username",
    "account.role": "Role",
    "account.selectRole": "Select role",
    "account.admin": "Admin",
    "account.staff": "Staff",
    "account.password": "Password",
    "account.keepCurrent": "(Leave blank to keep current)",
    "account.activeAccount": "Active Account",
    "account.canLogin": "User can login and access the system",
    "account.cancel": "Cancel",
    "account.createUser": "Create User",
    "account.updateUser": "Update User",
    "account.you": "You",
    "account.active": "Active",
    "account.inactive": "Inactive",
    "account.created": "Created:",
    "account.deactivate": "Deactivate",
    "account.activate": "Activate",
    "account.cannotDelete": "Cannot Delete",
    "account.cannotDeleteSelf": "You cannot delete your own account",
    "account.confirmDelete": "Are you sure you want to delete user",
    "account.profileUpdated": "Profile updated successfully",
    "account.userCreated": "User created successfully",
    "account.userUpdated": "User updated successfully",
    "account.userDeleted": "User deleted successfully",
    "account.updateFailed": "Failed to update profile",
    "account.createFailed": "Failed to create user",
    "account.updateUserFailed": "Failed to update user",
    "account.deleteFailed": "Failed to delete user",
    "account.incorrectPassword": "Current password is incorrect",
    "account.loginError": "Login error occurred",
    
    // Cart & Checkout Notices
    "cart.vatNotice": "Prices listed exclude 8% VAT",
    "cart.deliveryNotice": "Delivery service is temporarily unavailable. Please arrange your own delivery or pick up at the restaurant; our team can only assist in connecting you with a courier.",
  },
  vi: {
    // Navigation
    "nav.home": "Trang Chủ",
    "nav.menu": "Thực Đơn",
    "nav.about": "Giới Thiệu", 
    "nav.blog": "Blog",
    "nav.contact": "Liên Hệ",
    "nav.reservations": "Đặt Bàn",
    
    // Hero Section
    "hero.tagline": "PIZZA THỦ CÔNG VỚI LINH HỒN VIỆT NAM",
    "hero.title": "HUM'S PIZZA",
    "hero.subtitle": "Nơi pizza thủ công gặp gỡ hương vị Việt Nam. Tạo nên những khoảnh khắc đáng nhớ cho mọi gia đình thông qua món ăn ngon và trải nghiệm ấm áp.",
    "hero.orderOnline": "Đặt Món Online",
    "hero.bookTable": "Đặt Bàn",
    "hero.orderMenu": "Đặt Món",
    
    // Menu
    "menu.appetizers": "Khai Vị",
    "menu.mainCourse": "Món Chính",
    "menu.desserts": "Tráng Miệng",
    "menu.beverages": "Đồ Uống",
    "menu.available": "Còn món",
    "menu.soldOut": "Hết món",
    "menu.addToCart": "Thêm vào giỏ",
    "menu.featuredDishes": "Món Ăn Đặc Sắc",
    "menu.all": "Tất Cả", 
    "menu.ourSignatureDishes": "Các Món Đặc Trưng",
    "menu.viewFullMenu": "Xem Thực Đơn Đầy Đủ",
    "menu.searchPlaceholder": "Tìm kiếm món ăn...",
    "menu.subtitle": "Khám phá bộ sưu tập đầy đủ các món ăn Việt Nam và quốc tế, mỗi món được chế biến từ nguyên liệu cao cấp và kỹ thuật truyền thống",
    "menu.searchOurMenu": "Tìm kiếm thực đơn...",
    "menu.noItemsFound": "Không tìm thấy món ăn phù hợp với tìm kiếm của bạn.",
    "menu.allItems": "Tất Cả Món Ăn", 
    "menu.tryAdjusting": "Thử điều chỉnh từ khóa tìm kiếm hoặc duyệt tất cả danh mục.",
    
    // Category translations  
    "category": "Danh mục",
    "category.appetizers": "Khai Vị",
    "category.mainCourses": "Món Chính",
    "category.desserts": "Tráng Miệng", 
    "category.teaSelection": "Trà Đặc Biệt",
    "category.beverages": "Đồ Uống",
    "category.soups": "Canh Súp",
    
    // Customization Management  
    "customization.management": "Quản Lý Schema Tùy Biến",
    "customization.addCustomization": "Tùy Biến",
    "customization.createNew": "Tạo Schema Mới",
    "customization.editSchema": "Chỉnh Sửa Schema",
    "customization.nameEn": "Tên (English)",
    "customization.nameVi": "Tên (Tiếng Việt)",
    "customization.descriptionEn": "Mô tả (English)",
    "customization.descriptionVi": "Mô tả (Tiếng Việt)",
    "customization.schemaType": "Loại Schema",
    "customization.sizeSelection": "Chọn Kích Thước",
    "customization.halfAndHalf": "Half & Half Pizza",
    "customization.additionalToppings": "Topping Thêm",
    "customization.comboConfiguration": "Cấu Hình Combo",
    "customization.serviceFee": "Phí Dịch Vụ",
    "customization.addComboItem": "Thêm Món Combo",
    "customization.comboPrice": "Giá Combo",
    "customization.originalPrice": "Giá Gốc",
    "customization.discountAmount": "Số Tiền Giảm",
    "customization.save": "Lưu",
    "customization.cancel": "Hủy",
    "customization.delete": "Xóa", 
    "customization.edit": "Sửa",
    "customization.activate": "Kích Hoạt",
    "customization.active": "Kích Hoạt",
    "customization.createSuccess": "Tạo schema thành công!",
    "customization.updateSuccess": "Cập nhật schema thành công!",
    "customization.deleteSuccess": "Xóa schema thành công!",
    "customization.cloneSuccess": "Sao chép schema thành công!",
    "customization.confirmDelete": "Bạn có chắc chắn muốn xóa schema này?",
    "customization.selectSchemaType": "Chọn loại schema",
    "customization.priceConfig": "Cấu Hình Giá",
    "customization.halfAndHalfFee": "Phí Dịch Vụ Half & Half (VND)",
    "customization.size18cmPrice": "Giá Size 18cm (+VND)",
    
    // Privacy Policy
    "privacy.title": "Chính Sách Bảo Mật",
    "privacy.lastUpdated": "Cập nhật lần cuối",
    "privacy.date": "13 tháng 8, 2025",
    "privacy.section1.title": "Thông Tin Chúng Tôi Thu Thập",
    "privacy.section1.content1": "Tại Hum's Pizza, chúng tôi thu thập thông tin mà bạn cung cấp trực tiếp cho chúng tôi, chẳng hạn như khi bạn đặt bàn, đặt món hoặc liên hệ với chúng tôi để được hỗ trợ khách hàng.",
    "privacy.section1.content2": "Chúng tôi cũng có thể tự động thu thập một số thông tin nhất định về thiết bị của bạn và cách bạn tương tác với trang web của chúng tôi, bao gồm địa chỉ IP, loại trình duyệt và các trang đã truy cập.",
    "privacy.section2.title": "Thông Tin Cá Nhân",
    "privacy.section2.content1": "Các loại thông tin cá nhân chúng tôi có thể thu thập bao gồm:",
    "privacy.section2.item1": "Tên và thông tin liên hệ (email, số điện thoại)",
    "privacy.section2.item2": "Chi tiết đặt bàn và sở thích ăn uống",
    "privacy.section2.item3": "Lịch sử đặt món và thông tin thanh toán", 
    "privacy.section2.item4": "Tùy chọn liên lạc và phản hồi",
    "privacy.section3.title": "Cách Chúng Tôi Sử Dụng Thông Tin",
    "privacy.section3.content1": "Chúng tôi sử dụng thông tin thu thập được để:",
    "privacy.section3.item1": "Xử lý đặt bàn và đặt món",
    "privacy.section3.item2": "Cung cấp dịch vụ và hỗ trợ khách hàng",
    "privacy.section3.item3": "Gửi cho bạn cập nhật về nhà hàng và dịch vụ",
    "privacy.section3.item4": "Cải thiện trang web và trải nghiệm ăn uống",
    "privacy.section4.title": "Chia Sẻ Thông Tin",
    "privacy.section4.content": "Chúng tôi không bán, trao đổi hoặc chuyển giao thông tin cá nhân của bạn cho bên thứ ba mà không có sự đồng ý của bạn, trừ khi được mô tả trong Chính sách Bảo mật này hoặc theo yêu cầu của pháp luật.",
    "privacy.section5.title": "Bảo Mật Dữ Liệu", 
    "privacy.section5.content": "Chúng tôi thực hiện các biện pháp bảo mật thích hợp để bảo vệ thông tin cá nhân của bạn khỏi truy cập, thay đổi, tiết lộ hoặc phá hủy trái phép.",
    "privacy.section6.title": "Liên Hệ",
    "privacy.section6.content1": "Nếu bạn có bất kỳ câu hỏi nào về Chính sách Bảo mật này hoặc các thực hành bảo mật của chúng tôi, vui lòng liên hệ với chúng tôi tại:",
    "privacy.contact.email": "Email",
    "privacy.contact.phone": "Điện thoại", 
    "privacy.contact.address": "Địa chỉ",
    
    // Terms of Service
    "terms.title": "Điều Khoản Dịch Vụ",
    "terms.lastUpdated": "Cập nhật lần cuối",
    "terms.date": "13 tháng 8, 2025",
    "terms.section1.title": "Chấp Nhận Điều Khoản",
    "terms.section1.content1": "Bằng cách truy cập và sử dụng trang web và dịch vụ của Hum's Pizza, bạn chấp nhận và đồng ý bị ràng buộc bởi các điều khoản và quy định của thỏa thuận này.",
    "terms.section1.content2": "Nếu bạn không đồng ý tuân thủ những điều trên, vui lòng không sử dụng dịch vụ này.",
    "terms.section2.title": "Giấy Phép Sử Dụng",
    "terms.section2.content1": "Được phép tạm thời tải xuống một bản sao tài liệu trên trang web của Hum's Pizza chỉ để xem cá nhân, không thương mại. Đây là việc cấp giấy phép, không phải chuyển quyền sở hữu, và theo giấy phép này bạn không được:",
    "terms.section2.item1": "Sửa đổi hoặc sao chép tài liệu",
    "terms.section2.item2": "Sử dụng tài liệu cho mục đích thương mại hoặc hiển thị công khai",
    "terms.section2.item3": "Cố gắng dịch ngược bất kỳ phần mềm nào có trong trang web",
    "terms.section2.item4": "Xóa bất kỳ bản quyền hoặc ký hiệu độc quyền nào khỏi tài liệu",
    "terms.section3.title": "Tuyên Bố Từ Chối Trách Nhiệm",
    "terms.section3.content": "Các tài liệu trên trang web của Hum's Pizza được cung cấp trên cơ sở 'như hiện tại'. Hum's Pizza không đưa ra bảo đảm nào, dù rõ ràng hay ngụ ý, và từ chối tất cả các bảo đảm khác bao gồm không giới hạn, bảo đảm ngụ ý về khả năng bán được, phù hợp cho mục đích cụ thể, hoặc không vi phạm sở hữu trí tuệ.",
    "terms.section4.title": "Giới Hạn",
    "terms.section4.content": "Trong mọi trường hợp, Hum's Pizza hoặc các nhà cung cấp của chúng tôi sẽ không chịu trách nhiệm về bất kỳ thiệt hại nào (bao gồm, không giới hạn, thiệt hại do mất dữ liệu hoặc lợi nhuận, hoặc do gián đoạn kinh doanh) phát sinh từ việc sử dụng hoặc không thể sử dụng tài liệu trên trang web.",
    "terms.section5.title": "Thông Tin Liên Hệ",
    "terms.section5.content1": "Nếu bạn có bất kỳ câu hỏi nào về Điều khoản Dịch vụ này, vui lòng liên hệ với chúng tôi tại:",
    "terms.contact.email": "Email",
    "terms.contact.phone": "Điện thoại",
    "terms.contact.address": "Địa chỉ",
    
    // Accessibility
    "accessibility.title": "Tuyên Bố Khả Năng Truy Cập",
    "accessibility.lastUpdated": "Cập nhật lần cuối",
    "accessibility.date": "13 tháng 8, 2025",
    "accessibility.section1.title": "Cam Kết Của Chúng Tôi",
    "accessibility.section1.content": "Hum's Pizza cam kết đảm bảo khả năng truy cập kỹ thuật số cho người khuyết tật. Chúng tôi liên tục cải thiện trải nghiệm người dùng cho tất cả mọi người và áp dụng các tiêu chuẩn khả năng truy cập liên quan.",
    "accessibility.section2.title": "Tính Năng Khả Năng Truy Cập",
    "accessibility.section2.item1": "Hỗ trợ điều hướng bằng bàn phím",
    "accessibility.section2.item2": "Tương thích với trình đọc màn hình",
    "accessibility.section2.item3": "Tùy chọn màu độ tương phản cao",
    "accessibility.section2.item4": "Văn bản và các yếu tố giao diện có thể mở rộng",
    "accessibility.section3.title": "Phản Hồi",
    "accessibility.section3.content": "Chúng tôi hoan nghênh phản hồi của bạn về khả năng truy cập của Hum's Pizza. Vui lòng cho chúng tôi biết nếu bạn gặp phải các rào cản về khả năng truy cập trên trang web của chúng tôi.",
    "accessibility.section4.title": "Liên Hệ",
    "accessibility.section4.content1": "Nếu bạn có mối quan tâm hoặc đề xuất về khả năng truy cập, vui lòng liên hệ với chúng tôi:",
    "accessibility.contact.email": "Email",
    "accessibility.contact.phone": "Điện thoại",
    "accessibility.contact.address": "Địa chỉ",
    
    // Featured Sections
    "featured.title": "Trải Nghiệm Xuất Sắc",
    "featured.signature.title": "Pizza Thủ Công Đặc Biệt",
    "featured.signature.description": "Pizza được làm thủ công với hương vị Việt Nam, từ bột tươi mỗi ngày đến topping đặc biệt",
    "featured.atmosphere.title": "Không Gian Ấm Cúng",
    "featured.atmosphere.description": "Môi trường gia đình ấm áp, hoàn hảo cho mọi buổi sum họp và kỷ niệm",
    "featured.service.title": "Phục Vụ Tận Tâm",
    "featured.service.description": "Sự chăm sóc chu đáo từ đội ngũ yêu pizza và quý khách hàng",
    
    // Reservation Section
    "reservation.title": "Đặt Bàn Trải Nghiệm",
    "reservation.subtitle": "Đặt bàn và để chúng tôi tạo nên hành trình ẩm thực khó quên dành cho bạn",
    "reservation.bookNow": "Đặt Bàn Ngay",
    
    // Reviews Section
    "reviews.title": "Khách Hàng Nói Gì", 
    "reviews.subtitle": "Những phản hồi chân thật từ khách hàng về trải nghiệm pizza thủ công tại Hum's Pizza",
    
    // Blog Section
    "blog.title": "Câu Chuyện Mới Nhất",
    "blog.subtitle": "Cập nhật những cuộc phiêu lưu ẩm thực và tin tức nhà hàng",
    "blog.whatsHappening": "Chuyện Gì Đang Xảy Ra",
    "blog.blogSubtitle": "Cập nhật những sự kiện mới nhất, pizza mới, cảm hứng ẩm thực, và câu chuyện hậu trường từ Hum's Pizza",
    "blog.readMore": "Đọc Thêm",
    "blog.readFullArticle": "Đọc Bài Viết Đầy Đủ",
    "blog.moreStories": "Các Câu Chuyện Khác",
    "blog.viewAll": "Xem Tất Cả Bài Viết",
    "blog.noPosts": "Chưa Có Bài Viết",
    "blog.noPostsDesc": "Chúng tôi đang chuẩn bị nội dung thú vị về hành trình ẩm thực của mình.",
    "blog.checkBack": "Hãy ghé lại để xem cập nhật, công thức nấu ăn, và câu chuyện hậu trường!",
    "blog.postNotFound": "Không Tìm Thấy Bài Đăng", 
    "blog.postNotFoundDesc": "Bài đăng bạn tìm kiếm không tồn tại hoặc đã bị xóa.",
    "blog.backToBlog": "Quay Lại Tin Tức",
    "blog.publishedBy": "Được xuất bản bởi",
    "blog.moreArticles": "Xem Thêm Bài Viết",
    
    // Booking
    "booking.title": "Đặt Bàn",
    "booking.date": "Ngày",
    "booking.time": "Giờ",
    "booking.selectTime": "Chọn Giờ",
    "booking.guests": "Số khách",
    "booking.guest": "Khách",
    "booking.name": "Họ và tên",
    "booking.email": "Email",
    "booking.emailOptional": "Email (Tùy chọn)",
    "booking.phone": "Số điện thoại", 
    "booking.requests": "Yêu cầu đặc biệt",
    "booking.requestsOptional": "Yêu cầu đặc biệt (Tùy chọn)",
    "booking.requestsPlaceholder": "Hạn chế chế độ ăn, dịp đặc biệt, sở thích chỗ ngồi...",
    "booking.confirm": "Xác nhận đặt bàn",
    "booking.confirming": "Đang xác nhận...",
    "booking.cancel": "Hủy",
    "booking.success": "Đặt bàn thành công!",
    "booking.successMessage": "Chúng tôi sẽ xác nhận và liên hệ khách trong thời gian sớm nhất.",
    
    // Admin
    "admin.menuManagement": "Quản Lý Thực Đơn",
    "admin.addItem": "Thêm Món Ăn",
    "admin.edit": "Chỉnh sửa",
    "admin.delete": "Xóa",
    "admin.name": "Tên món ăn",
    "admin.nameVi": "Tên món ăn (Tiếng Việt)",
    "admin.description": "Mô tả",
    "admin.descriptionVi": "Mô tả (Tiếng Việt)",
    "admin.price": "Giá",
    "admin.category": "Danh mục",
    "admin.image": "Hình ảnh",
    "admin.uploadImage": "Tải lên hình ảnh",
    "admin.tags": "Tags",
    "admin.status": "Trạng thái",
    "admin.available": "Còn món",
    "admin.unavailable": "Hết món",
    "admin.save": "Lưu",
    "admin.cancel": "Hủy",
    "admin.create": "Tạo mới",
    "admin.update": "Cập nhật",
    
    // Admin Dashboard - Additional
    "admin.dashboardTitle": "Bảng Điều Khiển Admin",
    "admin.welcomeBack": "Chào mừng trở lại",
    "admin.viewWebsite": "Xem Website", 
    "admin.logout": "Đăng Xuất",
    "admin.totalReservations": "Tổng Đặt Bàn",
    "admin.pendingReservations": "Đặt Bàn Chờ", 
    "admin.totalOrders": "Tổng Đơn Hàng",
    "admin.pendingOrders": "Đơn Hàng Chờ",
    "admin.reservationManagement": "Quản Lý Đặt Bàn",
    "admin.orderManagement": "Quản Lý Đơn Hàng",
    "admin.blogManagement": "Quản Lý Tin Tức", 
    "admin.reviewManagement": "Đánh Giá Khách Hàng",
    "admin.contactManagement": "Tin Nhắn Liên Hệ",
    
    // Tab names (shorter - Vietnamese)
    "admin.reservationTab": "Đặt Bàn",
    "admin.orderTab": "Đơn Hàng", 
    "admin.menuTab": "Menu",
    "admin.blogTab": "Tin Tức",
    "admin.reviewTab": "Đánh Giá",
    "admin.contactTab": "Tin Nhắn",
    "admin.reservationList": "Danh Sách Đặt Bàn",
    "admin.reservationSubtitle": "Quản lý các yêu cầu đặt bàn của khách hàng",
    "admin.orderList": "Danh Sách Đơn Hàng",
    "admin.orderSubtitle": "Quản lý các đơn hàng của khách hàng",
    "admin.reviewList": "Danh Sách Đánh Giá",
    "admin.reviewSubtitle": "Quản lý và kiểm duyệt đánh giá và phản hồi của khách hàng",
    "admin.contactList": "Tin Nhắn Liên Hệ",
    "admin.contactSubtitle": "Quản lý các yêu cầu và tin nhắn liên hệ của khách hàng",
    "admin.newsTitle": "Quản Lý Tin Tức",
    "admin.newsSubtitle": "Quản lý bài viết blog và tin tức", 
    "admin.searchReservations": "Tìm theo tên, số điện thoại, email...",
    "admin.searchOrders": "Tìm theo tên, email, mã đơn hàng...",
    "admin.allTime": "Tất cả",
    "admin.today": "Hôm nay",
    "admin.last7Days": "7 ngày qua", 
    "admin.last30Days": "1 tháng qua",
    "admin.last90Days": "3 tháng qua",
    "admin.last180Days": "6 tháng qua",
    "admin.showing": "Hiển thị",
    "admin.noReservationsFound": "Không tìm thấy đặt bàn phù hợp với bộ lọc",
    "admin.noOrdersFound": "Không tìm thấy đơn hàng phù hợp với bộ lọc",
    "admin.noReservations": "Chưa có đặt bàn nào",
    "admin.noOrders": "Chưa có đơn hàng nào",
    "admin.confirmBtn": "Xác Nhận",
    "admin.cancelBtn": "Hủy",
    // Status translations for buttons
    "admin.pending": "Đang Chờ",
    "admin.confirmed": "Đã Xác Nhận", 
    "admin.completed": "Hoàn Thành",
    "admin.cancelled": "Đã Hủy",
    "admin.preparing": "Đang Chuẩn Bị",
    "admin.ready": "Sẵn Sàng",
    
    // Status translations with suffix (for longer descriptions)
    "admin.confirmedStatus": "Đã Xác Nhận", 
    "admin.pendingStatus": "Đang Chờ",
    "admin.completedStatus": "Hoàn Thành",
    "admin.cancelledStatus": "Đã Hủy",
    "admin.selectItems": "Chọn món ăn để xem chi tiết...",
    "admin.reservations": "đặt bàn",
    "admin.orders": "đơn hàng",
    "admin.at": "lúc",
    "admin.people": "người",
    "admin.requests": "Yêu cầu",
    "admin.menuTitle": "Quản Lý Thực Đơn",
    "admin.menuSubtitle": "Thêm, sửa, xoá các món ăn và danh mục trong menu",
    "admin.homeManagement": "Quản Lý Trang Chủ",
    "admin.aboutManagement": "Quản Lý Giới Thiệu",
    "admin.menuItems": "Món Ăn",
    "admin.categories": "Danh Mục",
    "admin.manageCategories": "Quản Lý Danh Mục",
    "admin.manageCategoryItems": "Quản lý các món ăn trong menu",
    "admin.categoryManagement": "Quản Lý Danh Mục",
    "admin.addCategory": "Thêm Danh Mục",
    "admin.editCategory": "Chỉnh Sửa Danh Mục",
    "admin.categoryName": "Tên Danh Mục (Tiếng Anh)",
    "admin.categoryNameVi": "Tên Danh Mục (Tiếng Việt)",
    "admin.categoryDescription": "Mô Tả Danh Mục",
    "admin.sortOrder": "Thứ Tự Sắp Xếp",
    "admin.searchMenu": "Tìm theo tên món ăn, mô tả, tags...",
    "admin.allCategories": "Tất Cả Danh Mục",
    "admin.showingItems": "Hiển thị",
    "admin.itemsLabel": "món ăn",
    
    // Additional admin keys - Vietnamese
    "admin.customizationTab": "Tùy Biến",
    "admin.customizationManagement": "Quản Lý Tùy Biến",
    "admin.dineIn": "Tại Bàn",
    "admin.takeout": "Mang Đi", 
    "admin.delivery": "Giao Hàng",
    "admin.total": "Tổng",
    "admin.orderedItems": "Món Đã Đặt",
    "admin.selectItemToAdd": "Chọn món để thêm",
    "admin.searchFood": "Tìm món ăn...",
    "admin.add": "Thêm",
    "admin.noItemsFound": "Không tìm thấy món ăn với từ khóa",
    
    // Dashboard Statistics Cards - Vietnamese
    "admin.totalReservationsCard": "Tổng Đặt Bàn",
    "admin.totalOrdersCard": "Tổng Đơn Hàng",
    "admin.totalMessagesCard": "Tổng Tin Nhắn",
    
    // Search and Filters - Vietnamese  
    "admin.searchPlaceholder": "Tìm kiếm đặt bàn, đơn hàng, tin nhắn...",
    "admin.allTimeFilter": "Tất cả thời gian", 
    "admin.todayFilter": "Hôm nay",
    "admin.last7DaysFilter": "7 ngày qua",
    "admin.last30DaysFilter": "30 ngày qua", 
    "admin.last90DaysFilter": "90 ngày qua",
    "admin.saving": "Đang lưu...",
    
    // Home Management - Vietnamese
    "home.management.title": "Quản Lý Trang Chủ",
    "home.management.subtitle": "Quản lý nội dung trang chủ và video hero", 
    "home.hero.title": "Tiêu Đề Hero",
    "home.hero.titleVi": "Tiêu Đề Hero (Tiếng Việt)",
    "home.hero.titleEn": "Tiêu Đề Hero (Tiếng Anh)",
    "home.reservation.title": "Tiêu Đề Đặt Bàn",
    "home.reservation.titleVi": "Tiêu Đề Đặt Bàn (Tiếng Việt)",
    "home.reservation.titleEn": "Tiêu Đề Đặt Bàn (Tiếng Anh)",
    "home.reservation.subtitle": "Phụ Đề Đặt Bàn",
    "home.reservation.subtitleVi": "Phụ Đề Đặt Bàn (Tiếng Việt)",
    "home.reservation.subtitleEn": "Phụ Đề Đặt Bàn (Tiếng Anh)",
    "home.featured.title": "Tiêu Đề Nổi Bật",
    "home.featured.titleVi": "Tiêu Đề Nổi Bật (Tiếng Việt)",
    "home.featured.titleEn": "Tiêu Đề Nổi Bật (Tiếng Anh)",
    "home.featured.subtitle": "Phụ Đề Nổi Bật",
    "home.featured.subtitleVi": "Phụ Đề Nổi Bật (Tiếng Việt)",
    "home.featured.subtitleEn": "Phụ Đề Nổi Bật (Tiếng Anh)",
    "home.update": "Cập Nhật Trang Chủ",
    "home.videoHero": "Video Hero",
    "home.uploadMainVideo": "Tải lên Video Hero Chính",
    "home.uploadReservationVideo": "Tải lên Video Hero Phần Đặt Bàn",
    "home.mainVideoDesc": "Upload video nền cho phần hero chính (tối đa 200MB)",
    "home.reservationVideoDesc": "Upload video nền cho phần đặt bàn trải nghiệm (tối đa 200MB)",
    "home.uploadMainBtn": "Tải lên Video Hero",
    "home.uploadReservationBtn": "Tải lên Video Đặt Bàn",
    "home.videoNote": "Lưu ý: Video sẽ được sử dụng làm nền cho phần hero của trang chủ. Đảm bảo video có chất lượng tốt và phù hợp với thương hiệu nhà hàng.",
    "home.refresh": "Làm mới",
    "home.featuredSection.title": "Phần Món Đặc Trưng",
    "home.featuredSection.subtitle": "Tiêu đề của phần món ăn đặc trưng",
    "home.reservationSection.title": "Phần Đặt Bàn", 
    "home.reservationSection.subtitle": "Tiêu đề của phần đặt bàn trải nghiệm",
    "home.reviewsSection.title": "Phần Đánh Giá Khách Hàng",
    "home.reviewsSection.subtitle": "Tiêu đề của phần khách hàng nói gì",
    "home.blogSection.title": "Phần Tin Tức",
    "home.blogSection.subtitle": "Tiêu đề của phần câu chuyện mới nhất",
    "home.labels.titleEn": "Tiêu đề (English)",
    "home.labels.titleVi": "Tiêu đề (Tiếng Việt)",
    "home.labels.subtitleEn": "Phụ đề (English)",
    "home.labels.subtitleVi": "Phụ đề (Tiếng Việt)",
    
    // About Management - Vietnamese  
    "about.management.title": "Quản Lý Trang Giới Thiệu",
    "about.management.subtitle": "Quản lý nội dung trang giới thiệu và thông tin nhà hàng",
    "about.tabs.statistics": "Thống Kê", 
    "about.tabs.philosophy": "Triết Lý",
    "about.tabs.team": "Đội Ngũ",
    "about.story.title": "Tiêu Đề Câu Chuyện",
    "about.story.titleVi": "Tiêu Đề Câu Chuyện (Tiếng Việt)",
    "about.story.titleEn": "Tiêu Đề Câu Chuyện (Tiếng Anh)",
    "about.story.content": "Nội Dung Câu Chuyện",
    "about.story.contentVi": "Nội Dung Câu Chuyện (Tiếng Việt)",
    "about.story.contentEn": "Nội Dung Câu Chuyện (Tiếng Anh)",
    "about.mission.title": "Tiêu Đề Sứ Mệnh",
    "about.mission.titleVi": "Tiêu Đề Sứ Mệnh (Tiếng Việt)",
    "about.mission.titleEn": "Tiêu Đề Sứ Mệnh (Tiếng Anh)",
    "about.mission.content": "Nội Dung Sứ Mệnh",
    "about.mission.contentVi": "Nội Dung Sứ Mệnh (Tiếng Việt)",
    "about.mission.contentEn": "Nội Dung Sứ Mệnh (Tiếng Anh)",
    "about.update": "Cập Nhật Trang Giới Thiệu",
    
    // Login Page
    "login.title": "Hum's Pizza",
    "login.subtitle": "Đăng nhập vào dashboard quản trị",
    "login.username": "Tên đăng nhập",
    "login.password": "Mật khẩu",
    "login.loginButton": "Đăng nhập",
    "login.loggingIn": "Đang đăng nhập...",
    "login.demoInfo": "Thông tin đăng nhập demo:",
    "login.demoUsername": "Username:",
    "login.demoPassword": "Password:",
    
    // Account Settings
    "account.title": "Cài Đặt Tài Khoản",
    "account.subtitle": "Quản lý tài khoản và phân quyền người dùng",
    "account.myProfile": "Hồ Sơ Của Tôi",
    "account.userManagement": "Quản Lý Người Dùng",
    "account.profileInfo": "Thông Tin Hồ Sơ",
    "account.updateInfo": "Cập nhật thông tin cá nhân và thay đổi mật khẩu",
    "account.fullName": "Họ và Tên",
    "account.email": "Email",
    "account.changePassword": "Đổi Mật Khẩu",
    "account.currentPassword": "Mật Khẩu Hiện Tại",
    "account.newPassword": "Mật Khẩu Mới (Tùy Chọn)",
    "account.leaveBlank": "Để trống để giữ mật khẩu hiện tại",
    "account.confirmPassword": "Xác Nhận Mật Khẩu Mới",
    "account.updating": "Đang cập nhật...",
    "account.updateProfile": "Cập Nhật Hồ Sơ",
    "account.manageUsers": "Quản lý tài khoản admin và staff",
    "account.addUser": "Thêm Người Dùng",
    "account.editUser": "Sửa Người Dùng",
    "account.addNewUser": "Thêm Người Dùng Mới",
    "account.createAccount": "Tạo tài khoản admin hoặc staff mới",
    "account.updateAccount": "Cập nhật thông tin người dùng",
    "account.username": "Tên Đăng Nhập",
    "account.role": "Vai Trò",
    "account.selectRole": "Chọn vai trò",
    "account.admin": "Quản Trị Viên",
    "account.staff": "Nhân Viên",
    "account.password": "Mật Khẩu",
    "account.keepCurrent": "(Để trống để giữ mật khẩu hiện tại)",
    "account.activeAccount": "Tài Khoản Hoạt Động",
    "account.canLogin": "Người dùng có thể đăng nhập và truy cập hệ thống",
    "account.cancel": "Hủy",
    "account.createUser": "Tạo Người Dùng",
    "account.updateUser": "Cập Nhật Người Dùng",
    "account.you": "Bạn",
    "account.active": "Hoạt Động",
    "account.inactive": "Không Hoạt Động",
    "account.created": "Tạo lúc:",
    "account.deactivate": "Vô Hiệu Hóa",
    "account.activate": "Kích Hoạt",
    "account.cannotDelete": "Không Thể Xóa",
    "account.cannotDeleteSelf": "Bạn không thể xóa tài khoản của chính mình",
    "account.confirmDelete": "Bạn có chắc chắn muốn xóa người dùng",
    "account.profileUpdated": "Cập nhật hồ sơ thành công",
    "account.userCreated": "Tạo người dùng thành công",
    "account.userUpdated": "Cập nhật người dùng thành công",
    "account.userDeleted": "Xóa người dùng thành công",
    "account.updateFailed": "Cập nhật hồ sơ thất bại",
    "account.createFailed": "Tạo người dùng thất bại",
    "account.updateUserFailed": "Cập nhật người dùng thất bại",
    "account.deleteFailed": "Xóa người dùng thất bại",
    "account.incorrectPassword": "Mật khẩu hiện tại không đúng",
    "account.loginError": "Lỗi khi đăng nhập",
    
    // Footer
    "footer.hours": "Giờ Mở Cửa",
    "footer.contact": "Liên Hệ",
    "footer.contactUs": "Liên hệ với chúng tôi",
    "footer.address": "Địa chỉ",
    "footer.addressLine1": "108 Ngô Gia Tự, Phường Chánh Nghĩa",
    "footer.addressLine2": "Thủ Dầu Một, Bình Dương, Việt Nam",
    "footer.hotline": "Hotline",
    "footer.email": "Email",
    "footer.follow": "Theo Dõi Chúng Tôi",
    "footer.newsletter": "Bản Tin",
    "footer.subscribe": "Đăng ký nhận bản tin để cập nhật thông tin mới",
    "footer.emailPlaceholder": "Nhập email của bạn",
    "footer.subscribeBtn": "Đăng Ký",
    "footer.allRights": "Bảo lưu mọi quyền.",
    "footer.tagline": "Nơi nghệ thuật ẩm thực gặp gỡ truyền thống Việt Nam",
    
    // About Page
    "about.title": "Giới Thiệu Hum's Pizza",
    "about.subtitle": "Nơi pizza thủ công gặp gỡ lòng hiếu khách Việt Nam, tạo nên những kỷ niệm ấm áp cho mọi gia đình thông qua món ăn ngon và dịch vụ tận tâm.",
    "about.ourStory": "Câu Chuyện Của Chúng Tôi",
    "about.story1": "Hum's Pizza bắt đầu từ một cửa hàng nhỏ tại Bình Dương, nơi mọi thứ được xây dựng từ sự đam mê và tinh thần thủ công. Đội ngũ không chỉ học hỏi tinh hoa của pizza truyền thống từ Chicago hay Ý, mà còn dành thời gian nghiên cứu để điều chỉnh hương vị phù hợp với khẩu vị người Việt.",
    "about.story2": "Từ phần sốt, lớp nhân cho đến cách phục vụ đều được cân nhắc kỹ lưỡng để khách hàng cảm thấy gần gũi và dễ thưởng thức hơn. Không dừng lại ở việc làm ra một chiếc pizza ngon, Hum's Pizza còn mong muốn trở thành nơi lưu giữ những khoảnh khắc đáng nhớ.",
    "about.story3": "Mỗi bàn ăn đều có thể là nơi diễn ra một cuộc trò chuyện quan trọng, một buổi hẹn đầu tiên, hay chỉ đơn giản là phút giây cả gia đình cùng nhau dùng bữa. Đội ngũ luôn trân trọng điều đó và luôn hướng tới việc tạo ra không gian ấm cúng, chỉn chu.",
    "about.ourPhilosophy": "Triết Lý Của Chúng Tôi",

    "about.meetTeam": "Gặp Gỡ Đội Ngũ",

    // Statistics Section - Vietnamese
    "stats.recipes": "Công Thức Pizza Đặc Biệt",
    "stats.served": "Pizza Thủ Công Đã Phục Vụ",
    "stats.fresh": "Bột Pizza Tươi Mỗi Ngày",
    "stats.satisfaction": "Khách Hàng Hài Lòng",

    // Team Section - Vietnamese
    "team.chefHung": "Hùng Nguyễn",
    "team.chefHungTitle": "Bếp Trưởng & Người Sáng Lập",
    "team.chefHungDesc": "Với hơn 10 năm kinh nghiệm làm pizza, Hùng đã nghiên cứu và điều chỉnh công thức để tạo ra những chiếc pizza vừa giữ được tinh túy truyền thống vừa phù hợp với khẩu vị Việt Nam.",
    "team.mai": "Mai Phương",
    "team.maiTitle": "Quản Lý Nhà Hàng",
    "team.maiDesc": "Mai đảm bảo mọi khách hàng đều có trải nghiệm tuyệt vời nhất. Cô luôn lắng nghe phản hồi và liên tục cải thiện chất lượng dịch vụ để tạo ra không gian ấm cúng cho mọi gia đình.",
    "team.tuan": "Tuấn Anh",
    "team.tuanTitle": "Chuyên Gia Bột Pizza",
    "team.tuanDesc": "Tuấn chịu trách nhiệm về quy trình tạo bột và ủ bột hàng ngày. Anh đảm bảo mỗi chiếc pizza đều có đế giòn rụm, mềm mại và hương vị đặc trưng của pizza thủ công.",

    // Philosophy Section - Vietnamese
    "about.vision": "Tầm Nhìn",
    "about.visionDesc": "Hum's Pizza muốn xây dựng một chuỗi nhà hàng pizza của người Việt, đạt tiêu chuẩn quốc tế nhưng vẫn giữ được nét riêng. Mục tiêu không chỉ là mang đến món ăn chất lượng mà còn tạo ra sự gắn kết và những trải nghiệm đáng nhớ.",
    "about.mission": "Sứ Mệnh",
    "about.missionDesc": "Làm pizza thủ công với chất lượng ổn định, hương vị hài hòa và phục vụ tận tâm. Tạo ra trải nghiệm từ mùi hương, hương vị, không gian đến dịch vụ. Tin rằng những kỷ niệm đẹp bắt đầu từ những điều đơn giản như một chiếc pizza ngon.",
    "about.values": "Giá Trị Cốt Lõi",
    "about.valuesDesc": "Chúng tôi tin vào chất lượng thủ công, sự tận tâm trong từng món ăn và tạo ra không gian ấm cúng nơi mọi gia đình có thể cùng nhau tạo nên những khoảnh khắc đáng nhớ qua bữa ăn ngon.",
    
    // Contact Page
    "contact.title": "Liên Hệ Với Chúng Tôi",
    "contact.subtitle": "Liên hệ với chúng tôi để đặt bàn, hỏi thông tin hoặc tổ chức sự kiện đặc biệt",
    "contact.visitUs": "Ghé Thăm Chúng Tôi",
    "contact.address": "Địa Chỉ",
    "contact.phone": "Điện Thoại",
    "contact.email": "Email",
    "contact.hours": "Giờ Mở Cửa",
    "contact.sendMessage": "Gửi Tin Nhắn Cho Chúng Tôi",
    "contact.yourName": "Tên Của Bạn",
    "contact.yourEmail": "Email Của Bạn",
    "contact.yourPhone": "Số Điện Thoại Của Bạn",
    "contact.subject": "Chủ Đề",
    "contact.message": "Tin Nhắn Của Bạn",
    "contact.sendBtn": "Gửi Tin Nhắn",
    "contact.sending": "Đang gửi...",
    "contact.messageSent": "Đã Gửi Tin Nhắn!",
    "contact.messageSuccess": "Chúng tôi sẽ phản hồi bạn sớm nhất có thể.",
    "contact.messageFailed": "Gửi Tin Nhắn Thất Bại",
    

    
    // Legal Pages
    "legal.privacyPolicy": "Chính Sách Bảo Mật",
    "legal.termsOfService": "Điều Khoản Dịch Vụ",
    "legal.accessibility": "Khả Năng Tiếp Cận",
    "legal.navigation": "Điều Hướng",
    "legal.legalText": "Pháp Lý",
    
    // Common
    "common.loading": "Đang tải...",
    "common.error": "Lỗi",
    "common.success": "Thành công",
    "common.close": "Đóng",
    "common.home": "Trang Chủ",
    "common.menu": "Thực Đơn",
    "common.about": "Giới Thiệu",
    "common.blog": "Tin Tức",
    "common.contact": "Liên Hệ",
    "common.booking": "Đặt Bàn",
    
    // Cart & Checkout Notices
    "cart.vatNotice": "Giá trên chưa bao gồm 8% VAT",
    "cart.deliveryNotice": "Tạm thời chưa cung cấp dịch vụ giao hàng. Quý khách vui lòng tự đặt giao hàng hoặc nhận tại nhà hàng, đội ngũ chỉ có thể hỗ trợ kết nối shipper.",
    
    // Admin Dashboard - Vietnamese translations
    "admin.orderType": "Loại Đơn Hàng",
    "admin.editOrder": "Chỉnh Sửa Đơn Hàng"
  }
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem("language");
      return (saved as Language) || "vi"; // Default to Vietnamese
    }
    return "vi"; // Default to Vietnamese for SSR
  });

  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem("language", language);
    }
  }, [language]);

  // Wrapper function to mark when user manually changes language
  const setLanguage = (lang: Language) => {
    if (typeof window !== 'undefined') {
      // Mark that user manually changed language (for blog post redirect logic)
      sessionStorage.setItem('user-language-changed', 'true');
    }
    setLanguageState(lang);
  };

  const t = (key: string, fallback?: string) => {
    const translation = translations[language][key as keyof typeof translations[typeof language]];
    return translation || fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

// Hook for content translation
export function useContent(content: { en?: string; vi?: string }, fallback?: string) {
  const { language } = useLanguage();
  
  if (language === "vi" && content.vi) {
    return content.vi;
  }
  
  if (language === "en" && content.en) {
    return content.en;
  }
  
  // Fallback logic
  return content.vi || content.en || fallback || "";
}